allowBuilds:
  "@apollo/protobufjs": true
  "@datadog/pprof": true
  "@parcel/watcher": true
  esbuild: true
  protobufjs: true
overrides:
  date-fns: "4.3.0"
  vite: "8.0.14"
  rolldown: "1.0.2"
  "@powerhousedao/connect": "link:/Users/benjaminjordan/projects/powerhouse/powerhouse-feature-0/apps/connect"
  "@powerhousedao/reactor-browser": "link:/Users/benjaminjordan/projects/powerhouse/powerhouse-feature-0/packages/reactor-browser"
